# Generated by Django 5.2a1 on 2026-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='websiteUri',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
