# Generated by Django 6.0.3 on 2026-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_groupmembership_role_alter_place_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
