# Generated by Django 6.0.3 on 2026-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
