# Generated by Django 5.2a1 on 2025-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_end_date_trip_location_trip_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
