# Generated by Django 5.2a1 on 2025-12-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_group_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photoURI', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.AddField(
            model_name='trip',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.place'),
        ),
    ]
