# Generated by Django 5.2a1 on 2026-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_post_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
