# Generated by Django 5.2a1 on 2026-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_through_to_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.IntegerField(default=50),
        ),
    ]
